### ISSUE TITLE
c or c++ for taint analysis

### ISSUE THREAD

**Issue by Waterman178** [TrustedSoftware-XJTU/taint-analysis-results#1]
Is there a taint analysis algorithm implemented by c or c++?And it supports backward and forward analysis.

**Comment by ZHYfeng** [comment]
https://ieeexplore.ieee.org/abstract/document/8472790
This is the paper of those result.
It could analysis multi-threaded c code and support forward.
If you do not need multi-threaded, there should be many normal tools.
